version: '3.7'

services:
  anime-bot:
    container_name: anime-bot
    image: anime-bot
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    volumes:
      - ./app:/app
      - ./.aws:/root/.aws
    env_file:
      - ./app/twitter_api.env
    tty: true
